// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool get isConfigured => true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-7jrbmODCbdJ5Chup9q7uUxr89he6v0',
    appId: '1:231156823209:web:b6af0eb3896102fd4625b8',
    messagingSenderId: '231156823209',
    projectId: 'tmk-53',
    authDomain: 'tmk-53.firebaseapp.com',
    storageBucket: 'tmk-53.firebasestorage.app',
    measurementId: 'G-6ZH82352JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwdcLHmo1e5-HdqZDUHIh5jbgp8DuNHQ',
    appId: '1:56471954569:android:3184c6de242d3c70751258',
    messagingSenderId: '56471954569',
    projectId: 'taherijamaat5253',
    databaseURL: 'https://taherijamaat5253.firebaseio.com',
    storageBucket: 'taherijamaat5253.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpLBf9eDeULV1xeJnbn3jIrpTE7Wibg8',
    appId: '1:56471954569:ios:3826899a23e2c105751258',
    messagingSenderId: '56471954569',
    projectId: 'taherijamaat5253',
    databaseURL: 'https://taherijamaat5253.firebaseio.com',
    storageBucket: 'taherijamaat5253.firebasestorage.app',
    iosBundleId: 'com.tmkkuwait.tmkKuwait',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-7jrbmODCbdJ5Chup9q7uUxr89he6v0',
    appId: '1:231156823209:web:2bbce4353485ea1d4625b8',
    messagingSenderId: '231156823209',
    projectId: 'tmk-53',
    authDomain: 'tmk-53.firebaseapp.com',
    storageBucket: 'tmk-53.firebasestorage.app',
    measurementId: 'G-14TJ7XVYEX',
  );
}
